spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver